name: BigDavesNewsApp
options:
  bundleIdPrefix: com.bigdavesnews
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.bigdavesnews.app
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: LSL6634TAV
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  configs:
    Debug:
      APS_ENVIRONMENT: development
    Release:
      APS_ENVIRONMENT: production
targets:
  BigDavesNewsApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/BigDavesNewsApp.entitlements
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
